package id.ac.ui.cs.advprog.eshop.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import jakarta.validation.ConstraintViolation;
import jakarta.validation.Validation;
import jakarta.validation.Validator;
import jakarta.validation.ValidatorFactory;

import java.util.Set;
import static org.junit.jupiter.api.Assertions.*;

class ProductTest {
    private Product product;
    private Validator validator;

    @BeforeEach
    void setUp() {
        product = new Product();
        product.setProductId("eb558e9f-1c39-460e-8860-71af6af63bd6");
        product.setProductName("Sampo Cap Bambang");
        product.setProductQuantity(100);

        // Initialize validator for constraint checks
        ValidatorFactory factory = Validation.buildDefaultValidatorFactory();
        validator = factory.getValidator();
    }

    @Test
    void testGetProductId() {
        assertEquals("eb558e9f-1c39-460e-8860-71af6af63bd6", product.getProductId());
    }

    @Test
    void testGetProductName() {
        assertEquals("Sampo Cap Bambang", product.getProductName());
    }

    @Test
    void testGetProductQuantity() {
        assertEquals(100, product.getProductQuantity());
    }

    @Test
    void testProductConstructor_WithId() {
        Product newProduct = new Product("12345", "Laptop", 50);
        assertEquals("12345", newProduct.getProductId());
        assertEquals("Laptop", newProduct.getProductName());
        assertEquals(50, newProduct.getProductQuantity());
    }

    @Test
    void testProductConstructor_AutoGeneratedId() {
        Product newProduct = new Product(null, "Tablet", 30);
        assertNotNull(newProduct.getProductId());  // Should generate a UUID
        assertEquals("Tablet", newProduct.getProductName());
        assertEquals(30, newProduct.getProductQuantity());
    }

    @Test
    void testSetProductId() {
        product.setProductId("new-product-id");
        assertEquals("new-product-id", product.getProductId());
    }

    @Test
    void testSetProductName() {
        product.setProductName("Sabun Mandi");
        assertEquals("Sabun Mandi", product.getProductName());
    }

    @Test
    void testSetProductQuantity() {
        product.setProductQuantity(200);
        assertEquals(200, product.getProductQuantity());
    }

    @Test
    void testProductName_NotBlank() {
        product.setProductName("");
        Set<ConstraintViolation<Product>> violations = validator.validate(product);
        assertFalse(violations.isEmpty());
    }

    @Test
    void testProductQuantity_NotNull() {
        product.setProductQuantity(null);
        Set<ConstraintViolation<Product>> violations = validator.validate(product);
        assertFalse(violations.isEmpty());
    }

    @Test
    void testProductQuantity_MinValue() {
        product.setProductQuantity(-1);  // Should trigger validation failure
        Set<ConstraintViolation<Product>> violations = validator.validate(product);
        assertFalse(violations.isEmpty());
    }
}
